[".local/share/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
refreshPeriod = "168h"

[".local/share/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".local/share/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"

[".local/share/fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
refreshPeriod = "168h"

